### PR TITLE
Fix upstream PR

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
Updates to make build pass:
- Merge upstream main
- Add changelog entry

Upstream PR:
- https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/92

### CODE REVIEW

**Comment by oxeye-gal** [comment]
Thanks @MikeGoldsmith, seems like the build is still fails, let me know if I can assist with fixing it.

**Comment by MikeGoldsmith** [comment]
@oxeye-gal looks like that was a bad merge conflict which resulted in an unused go variable. Should be fixed now.

**Comment by MikeGoldsmith** [comment]
Ah, I see the linter errors -- I'll update 👍🏻

**Comment by MikeGoldsmith** [comment]
@oxeye-gal  ready to run again

**Comment by oxeye-gal** [comment]
Thanks again @MikeGoldsmith , seems like it can be merged now :)

**Pull request merged**
